### ISSUE TITLE
RF03 - Editar usuario

### ISSUE THREAD

**Issue by andres174** [andres174/arqlaser-backend#4]
### Controlador - UsuarioController
En la función correspondiente implementar la lógica para actualizar los datos del usuario
### Rutas
Definir la ruta para la función 
A esta ruta solo se puede acceder si esta autenticado (middleware)
### Validaciones
Validar los datos recibidos (formato y obligatoriedad)
### Manejo de errores 
Enviar respuestas el cliente en caso de éxito o error

**Comment by gabriel12QK** [comment]
queda pendiente lo del middleware
